networks:
  kafka_net:
    driver: bridge

services:
  mongodb:
    image: 'mongo:latest'
    container_name: mongo-controle-despesa
    environment:
      - 'MONGO_INITDB_ROOT_PASSWORD=root'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'
  zookeeper:
    image: bitnami/zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - kafka_net
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes
      ZOOKEEPER_CLIENT_PORT: 2181
    #      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: bitnami/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    links:
      - zookeeper:zookeeper
    networks:
      - kafka_net
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper